### list popular movies
GET http://localhost:3000/api/movies/popular HTTP/1.1

### list top rated movies
GET http://localhost:3000/api/movies/top_rated HTTP/1.1

### get movie likes
GET http://localhost:3000/api/movies/120/likes HTTP/1.1

### add like to movie
POST http://localhost:3000/api/movies/120/likes HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQzNjIzMjk3LCJleHAiOjE2NDM2MjQxOTd9.vMxD8ILNF7UdpYRivsYTeHg_D4962nAOzCw8BffWcOs

### remove movie like
DELETE http://localhost:3000/api/movies/120/likes/1 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQzNjIzMjk3LCJleHAiOjE2NDM2MjQxOTd9.vMxD8ILNF7UdpYRivsYTeHg_D4962nAOzCw8BffWcOs

### get person likes
GET http://localhost:3000/api/persons/1/likes HTTP/1.1

### add like to person
POST http://localhost:3000/api/persons/1/likes HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQzNjI1NzIxLCJleHAiOjE2NDM2MjY2MjF9.2sKyoVLbOxvl5Lb9ybJCnjeDBQ2Nlep6crJ_oqkd3fk

### remove person like
DELETE http://localhost:3000/api/persons/1/likes/3 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQzNjI1NzIxLCJleHAiOjE2NDM2MjY2MjF9.2sKyoVLbOxvl5Lb9ybJCnjeDBQ2Nlep6crJ_oqkd3fk

### list genres
GET http://localhost:3000/api/genres HTTP/1.1

### get person
GET http://localhost:3000/api/persons/1 HTTP/1.1

### popular persons
GET http://localhost:3000/api/persons/popular HTTP/1.1

### persons credits
GET http://localhost:3000/api/persons/123/credits HTTP/1.1

### create user
POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
  "name": "Jenny Doe",
  "password": "12345",
  "email" : "joe@yahoo.com"
}

### login
POST http://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
  "email" : "joe@yahoo.com",
  "password": "12345"
}

### refresh token
POST http://localhost:3000/api/users/token HTTP/1.1
content-type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjQzNDAxNzkwfQ.LeFwS8okyq9cudBjkSgfSRCJyWNDZaSSJGQTw2UZolg"
}

### list users
GET http://localhost:3000/api/users HTTP/1.1

### get user by id
GET http://localhost:3000/api/users/1 HTTP/1.1
